### ISSUE TITLE
Helpful suggestion?

### ISSUE THREAD

**Issue by jrowellfx** [Digitante/lsseq#1]
I see that you wrote this as an exercise for yourself, but as you point out it is handy. If you really do need support for this kind of functionality, I highly recommend checking out my lsseq repo here on github. It's quite powerful, will give you what you want, plus has been tested and in use a lots of pre production studios around the world. 

Anyway, I hope you find this helpful! Thanks!

**Comment by filmfreedom-org** [comment]
Hmm. Your utility didn't show up in any of the searches I did when I first wrote mine and uploaded it 3 years ago, or I probably wouldn't have written it. I see yours has only been on GitHub a couple of months. Where had you published it previously?

Well, I suppose the name is fairly obvious for the functionality. Thanks for letting me know about the name collision.

**Comment by jrowellfx** [comment]
My pleasure. My repo has been on github since Dec 13, 2009. :-) No worries about name collisions I don't think it affects anything.  I was just searching github for lsseq and stumbled upon your code, so figured you might find mine helpful. Try installing it! Easy to do, that is, if you use linux or macos. I've never spent much time to get it to work on windows as there are so many different ways to run a linux-like shell, so I never bothered.  Anyway, thanks for the reply! Cheers! J.
